### ISSUE TITLE
Automatically register with conda installed h5py

### ISSUE THREAD

**Issue by carterbox** [conda-forge/hdf5plugin-feedstock#16]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

It seems that h5py expects for the plugins to be located in the folder `$CONDA_PREFIX/lib/hdf5/plugin` because when I try to read an hdf5 file that is compressed I get the following error:

```
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: Can't read data (can't open directory: /home/beams/DCHING/miniconda3/envs/punx/lib/hdf5/plugin)
```

I would like to add a link from `$CONDA_PREFIX/lib/hdf5/plugin` to `$CONDA_PREFIX/lib/python3.x/site-packages/hdf5plugin/plugins` because that is where h5py looks for plugins by default. I believe this behavior would still respect a user who sets the hdf5 plugin path, but it would automatically link the plugins to a conda installed hdf5.

```
$ conda list hdf5*
# packages in environment at /home/beams/DCHING/miniconda3/envs/punx:
#
# Name                    Version                   Build  Channel
hdf5                      1.10.6          nompi_h6a2412b_1113    conda-forge
hdf5plugin                2.3.2            py39h621bcbd_0    conda-forge
```

**Comment by carterbox** [comment]
Nevermind? I guess I was looking for the [`hdf5-external-filter-plugins`](https://github.com/conda-forge/hdf5-external-filter-plugins-feedstock) package with which this package shares source code.

**Comment by t20100** [comment]
There is 2 ways to have compression enabled in `h5py`:
- Putting the compression plugins in the directory where `libhdf5` is looking for them: this is `hdf5-external-filter-plugins`.
- Registering the compression plugins at runtime: this is `hdf5plugin`.

Main advantage of `hdf5plguin` is not when installing through conda but when installing `h5py` from a wheel from `pypi.org`.

**Comment by carterbox** [comment]
A wheel is precompiled, so it is similar to a conda package. Do you mean the advantage is installing from source through `pypi` allows compile-time-optimization for the end-user hardware?

**Comment by t20100** [comment]
No, though it is also true.
I was meaning that with `h5py` wheel you have no choice but to register the HDF5 compression plugins at runtime (that's what `hdf5plugin` targets in the first place), while with conda you can install them in the libhdf5 plugin directory.
