### ISSUE TITLE
Build flags for the next version of hdf5plugin

### ISSUE THREAD

**Issue by t20100** [conda-forge/hdf5plugin-feedstock#2]
Information for packaging next version of hdf5plugin:

PR https://github.com/silx-kit/hdf5plugin/pull/52 and https://github.com/silx-kit/hdf5plugin/pull/51 added some build options that are of importance for packaging.
Those options are:

* `--openmp`: Used for the bitshuffle filter
* `--native`: To optimize for the machine building the package
* `--sse2`: To enable SSE2 in the blosc filter (needs for an environment variable)
* `--avx2`: To enable AVX2 in the blosc filter (needs for an environment variable)
The bitshuffle filter is using SSE2 or AVX2 with `--native=True` or `--sse2=True` and `--avx2=True`.

What is used to build wheels on x86_64 is:
`python setup.py build --openmp=False --native=False --sse2=True --avx2=False bdist_wheel`
I think you will need the same.

**Comment by tschoonj** [comment]
Thanks for the info, I will keep it in mind

**Comment by t20100** [comment]
PR https://github.com/silx-kit/hdf5plugin/pull/54 also add a `--cpp11=[True|False]` flag for building the snappy compression in the blosc filter (which requires C++11).
Depending on the availability of C++11 in conda you also might want to set that.

For the wheels, we set it to False except for python3 on Windows where C++11 is available starting from python 3.5.

**Comment by t20100** [comment]
BTW, v2.1.0 is released and uploaded on pypi: https://pypi.org/project/hdf5plugin/2.1.0/
